//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merop_Guri
    {
        public int Id { get; set; }
        public int Id_Meropriyatiya { get; set; }
        public int Id_Aktivnosti { get; set; }
        public int Id_User_Guri { get; set; }
    
        public virtual Aktivnosti Aktivnosti { get; set; }
        public virtual Meropriyatiya Meropriyatiya { get; set; }
        public virtual User User { get; set; }
    }
}
