//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredDiplom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PartyEntities : DbContext
    {
        public PartyEntities()
            : base("name=PartyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aktivnosti> Aktivnosti { get; set; }
        public virtual DbSet<Aktivnosti_Meropriyatiya> Aktivnosti_Meropriyatiya { get; set; }
        public virtual DbSet<Merop_Guri> Merop_Guri { get; set; }
        public virtual DbSet<Meropriyatiya> Meropriyatiya { get; set; }
        public virtual DbSet<Pol> Pol { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
